/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface WCardInfo {
    'description': string;
    'logo': string;
    'name': string;
  }
}

declare global {


  interface HTMLWCardInfoElement extends Components.WCardInfo, HTMLStencilElement {}
  var HTMLWCardInfoElement: {
    prototype: HTMLWCardInfoElement;
    new (): HTMLWCardInfoElement;
  };
  interface HTMLElementTagNameMap {
    'w-card-info': HTMLWCardInfoElement;
  }
}

declare namespace LocalJSX {
  interface WCardInfo {
    'description'?: string;
    'logo'?: string;
    'name'?: string;
  }

  interface IntrinsicElements {
    'w-card-info': WCardInfo;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'w-card-info': LocalJSX.WCardInfo & JSXBase.HTMLAttributes<HTMLWCardInfoElement>;
    }
  }
}


